name: {{feature_name.snakeCase()}}
description: {{feature_name.snakeCase()}} feature
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  design_system:
    path: ../../design_system
  commons:
    path: ../../commons
  core:
    path: ../../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.7.1

flutter:
